steps:
  - name: "Build the Docker image"
    id: "build"
    command:
      - "docker"
      - "build"
      - "-t"
      - "gcr.io/quixotic-skill-402605/test-image:tag1"
      - "."

  - name: "Push the Docker image to Container Registry"
    id: "push"
    command:
      - "docker"
      - "push"
      - "gcr.io/quixotic-skill-402605/test-image:tag1"

  - name: "Deploy the Docker image to Cloud Run"
    id: "deploy"
    command:
      - "gcloud"
      - "run" 
      - "deploy"
      - "test-image"
      - "-c"
      - "gcr.io/quixotic-skill-402605/test-image:tag1"
      - "-r"
      - "us-west1"
