steps:
  # clone common
  - name: 'gcr.io/changtalk/git'
    args: ['clone', 'https://github.com/cobinding/gcp-docker-ci-cd.git']

  - name: 'maven:3.8.1-openjdk-17'
    entrypoint: mvn
    args: ['clean', 'package', '-Dmaven.test.skip=true']