steps:

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '-f', 'us-west1-docker.pkg.dev//quixotic-skill-402605/test/changtalk-reg', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/quixotic-skill-402605/test/changtalk-reg']

  # Deploy Container Image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [ 'compute', 'instances', 'create-with-container', 'server-1', '--container-image', '${_REGION}-docker.pkg.dev/quixotic-skill-402605/test/changtalk-reg']

###### LOG OPTIONS #######
options:
  logging: CLOUD_LOGGING_ONLY

###### substitutions #######
substitutions:
  _REGION: us-west1
 #  _PROJECT_ID: quixotic-skill-402605
 #  _REGISTRY: test
 #  _DOCKER_IMAGE: changtalk-reg


