steps:
  # clone common
  - name: 'gcr.io/changtalk/git'
    args: ['clone', 'https://sebin-chu@bitbucket.org/changtalk-local-test/cloudtest.git']

  - name: 'maven:3.8.1-openjdk-17'
    entrypoint: mvn
    args: ['clean', 'package', '-Dmaven.test.skip=true']

options:
  logging: CLOUD_LOGGING_ONLY